# Generated by Django 5.1.2 on 2024-12-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_name',
            field=models.CharField(max_length=150, verbose_name='College'),
        ),
        migrations.AlterField(
            model_name='program',
            name='prog_name',
            field=models.CharField(max_length=150, verbose_name='Program Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=25, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=25, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middlename',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Middle Name'),
        ),
    ]
